[package]
name = "ddupe"
version = "1.0.1"
edition = "2024"

[dependencies]
sha2 = "0.10"
walkdir = "2.5"
clap = { version = "4", features = ["derive"] }
colored = "2"
indicatif = "0.17"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
